services:
  yukio:
    container_name: yukio
    depends_on:
      - chrome
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile
    image: yrch1/shelob:latest
    networks:
      - rivendel
  hub:
    container_name: selenium_hub
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
      TZ: "Europe/Madrid"
    networks:
      - rivendel

  chrome:
    image: selenium/node-chrome
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
      TZ: "Europe/Berlin"
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    networks:
      - rivendel

networks:
  rivendel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16